version: "3.8"
services:
  db:
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=tortoise
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=tweets
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
